version: '3.9'

volumes:
  postgres_data: {}
  postgres_logs: {}
  solr_data: {}
  solr_logs: {}

services:
  db:
    image: postgres:17
    restart: always 
    shm_size: 256mb
    ports:
      - "5432:5432"
    volumes:
        - postgres_data:/var/lib/postgresql/data
        - postgres_logs:/var/log/postgresql
    environment:
      - POSTGRES_USER=fbs
      - POSTGRES_PASSWORD=fbs
      - POSTGRES_DB=fbs
      
  solr:
    build:
      context: ./solr
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8983:8983"
    environment:
      - SOLR_HEAP=512m
    volumes:
      - solr_data:/opt/solr/server/solr
      - solr_logs:/opt/solr/server/logs
      - ./solr/schema.xml:/opt/solr/server/solr/configsets/_default/conf/schema.xml
      - ./solr/solrconfig.xml:/opt/solr/server/solr/configsets/_default/conf/solrconfig.xml

  valkey:
    command: valkey-server  --appendonly no --save ""
    image: valkey/valkey:8
    ports:
      - "6379:6379"
